FROM ubuntu:latest

ENTRYPOINT ["/bin/bash"]
ENTRYPOINT ["/bin/bash", "-c", "echo Hello World !"]

RUN apt -y update
RUN apt install -y iputils-ping

  #  /bin/bash -c "apt -y update"
    #  /bin/bash -c "apt install -y iputils-ping"
    #  /bin/bash -c "ping 127.0.0.1" 

RUN /bin/bash